"""Synthetic product catalog and sample quizzes for end-to-end runs."""

from .types import (
    Archetype,
    ColorProfile,
    Gender,
    OutfitSlot,
    Product,
    QuizAnswers,
)


def _w(*entries: tuple[Archetype, float]) -> dict[Archetype, float]:
    return {a: w for a, w in entries}


CATALOG: list[Product] = [
    # ---- Tops ----
    Product(id="t1", name="Plain white tee", brand="Uniqlo", price=15,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["white"],
            tags=["basic"],
            archetype_weights=_w((Archetype.CASUAL, 0.8), (Archetype.MINIMALIST, 0.9))),
    Product(id="t2", name="Oxford shirt", brand="Charles Tyrwhitt", price=80,
            gender=Gender.MALE, slot=OutfitSlot.TOP, colors=["blue", "white"],
            tags=["work"],
            archetype_weights=_w((Archetype.FORMAL, 0.9), (Archetype.MINIMALIST, 0.5))),
    Product(id="t3", name="Tech hoodie", brand="Lululemon", price=110,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["black", "grey"],
            tags=["athleisure"],
            archetype_weights=_w((Archetype.SPORTY, 0.9), (Archetype.CASUAL, 0.4))),
    Product(id="t4", name="Vintage band tee", brand="Re/Done", price=70,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["faded black"],
            tags=["graphic"],
            archetype_weights=_w((Archetype.VINTAGE, 0.9), (Archetype.CASUAL, 0.5))),
    Product(id="t5", name="Cashmere crew", brand="John Smedley", price=180,
            gender=Gender.MALE, slot=OutfitSlot.TOP, colors=["navy"],
            tags=["winter"],
            archetype_weights=_w((Archetype.FORMAL, 0.7), (Archetype.MINIMALIST, 0.8))),
    Product(id="t6", name="Linen overshirt", brand="COS", price=95,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["sand", "cream"],
            tags=["summer"],
            archetype_weights=_w((Archetype.MINIMALIST, 0.8), (Archetype.CASUAL, 0.6))),
    Product(id="t7", name="Polo shirt", brand="Lacoste", price=85,
            gender=Gender.MALE, slot=OutfitSlot.TOP, colors=["white", "navy"],
            tags=["smart casual"],
            archetype_weights=_w((Archetype.CASUAL, 0.7), (Archetype.FORMAL, 0.5))),
    Product(id="t8", name="Running shell", brand="Patagonia", price=130,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["red", "black"],
            tags=["outdoor"],
            archetype_weights=_w((Archetype.SPORTY, 0.95), (Archetype.CASUAL, 0.3))),
    Product(id="t9", name="Tweed blazer", brand="Polo Ralph Lauren", price=290,
            gender=Gender.MALE, slot=OutfitSlot.TOP, colors=["brown", "olive"],
            tags=["heritage"],
            archetype_weights=_w((Archetype.VINTAGE, 0.85), (Archetype.FORMAL, 0.7))),
    Product(id="t10", name="Striped breton", brand="Saint James", price=65,
            gender=Gender.UNISEX, slot=OutfitSlot.TOP, colors=["navy", "white"],
            tags=["nautical"],
            archetype_weights=_w((Archetype.VINTAGE, 0.6), (Archetype.CASUAL, 0.7),
                                  (Archetype.MINIMALIST, 0.5))),

    # ---- Bottoms ----
    Product(id="b1", name="Chino", brand="Uniqlo", price=40,
            gender=Gender.MALE, slot=OutfitSlot.BOTTOM, colors=["beige", "navy"],
            tags=["casual smart"],
            archetype_weights=_w((Archetype.CASUAL, 0.7), (Archetype.MINIMALIST, 0.7),
                                  (Archetype.FORMAL, 0.4))),
    Product(id="b2", name="Wool trouser", brand="Suit Supply", price=160,
            gender=Gender.MALE, slot=OutfitSlot.BOTTOM, colors=["grey", "navy"],
            tags=["business"],
            archetype_weights=_w((Archetype.FORMAL, 0.95), (Archetype.MINIMALIST, 0.6))),
    Product(id="b3", name="Running tight", brand="Nike", price=70,
            gender=Gender.UNISEX, slot=OutfitSlot.BOTTOM, colors=["black"],
            tags=["sport"],
            archetype_weights=_w((Archetype.SPORTY, 0.95),)),
    Product(id="b4", name="Vintage 501 jeans", brand="Levi's", price=110,
            gender=Gender.UNISEX, slot=OutfitSlot.BOTTOM, colors=["indigo"],
            tags=["denim"],
            archetype_weights=_w((Archetype.VINTAGE, 0.85), (Archetype.CASUAL, 0.75))),
    Product(id="b5", name="Pleated trouser", brand="COS", price=95,
            gender=Gender.UNISEX, slot=OutfitSlot.BOTTOM, colors=["cream", "black"],
            tags=["modern"],
            archetype_weights=_w((Archetype.MINIMALIST, 0.85), (Archetype.FORMAL, 0.6))),
    Product(id="b6", name="Cargo pant", brand="Carhartt WIP", price=120,
            gender=Gender.UNISEX, slot=OutfitSlot.BOTTOM, colors=["khaki", "black"],
            tags=["utility"],
            archetype_weights=_w((Archetype.CASUAL, 0.85), (Archetype.SPORTY, 0.4))),
    Product(id="b7", name="Linen short", brand="Sunspel", price=85,
            gender=Gender.MALE, slot=OutfitSlot.BOTTOM, colors=["navy", "cream"],
            tags=["summer"],
            archetype_weights=_w((Archetype.MINIMALIST, 0.7), (Archetype.CASUAL, 0.6))),
    Product(id="b8", name="Corduroy trouser", brand="Polo Ralph Lauren", price=140,
            gender=Gender.MALE, slot=OutfitSlot.BOTTOM, colors=["brown", "olive"],
            tags=["heritage"],
            archetype_weights=_w((Archetype.VINTAGE, 0.9), (Archetype.CASUAL, 0.5))),
    Product(id="b9", name="Slim suit pant", brand="Hugo Boss", price=200,
            gender=Gender.MALE, slot=OutfitSlot.BOTTOM, colors=["black", "navy"],
            tags=["business"],
            archetype_weights=_w((Archetype.FORMAL, 0.95), (Archetype.MINIMALIST, 0.7))),
    Product(id="b10", name="Track pant", brand="Adidas", price=60,
            gender=Gender.UNISEX, slot=OutfitSlot.BOTTOM, colors=["black", "white"],
            tags=["athletic"],
            archetype_weights=_w((Archetype.SPORTY, 0.9), (Archetype.CASUAL, 0.5))),

    # ---- Shoes ----
    Product(id="s1", name="Stan Smith", brand="Adidas", price=100,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["white", "green"],
            tags=["sneaker"],
            archetype_weights=_w((Archetype.MINIMALIST, 0.8), (Archetype.CASUAL, 0.8))),
    Product(id="s2", name="Oxford brogue", brand="Loake", price=240,
            gender=Gender.MALE, slot=OutfitSlot.SHOES, colors=["brown"],
            tags=["dress"],
            archetype_weights=_w((Archetype.FORMAL, 0.95), (Archetype.VINTAGE, 0.6))),
    Product(id="s3", name="Air Max 90", brand="Nike", price=140,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["white", "red"],
            tags=["sneaker"],
            archetype_weights=_w((Archetype.SPORTY, 0.85), (Archetype.CASUAL, 0.7))),
    Product(id="s4", name="Chelsea boot", brand="R.M. Williams", price=400,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["brown", "black"],
            tags=["heritage"],
            archetype_weights=_w((Archetype.VINTAGE, 0.85), (Archetype.FORMAL, 0.7))),
    Product(id="s5", name="Achilles low", brand="Common Projects", price=380,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["white"],
            tags=["minimal"],
            archetype_weights=_w((Archetype.MINIMALIST, 0.95), (Archetype.FORMAL, 0.5))),
    Product(id="s6", name="Old Skool", brand="Vans", price=70,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["black", "white"],
            tags=["skate"],
            archetype_weights=_w((Archetype.CASUAL, 0.85), (Archetype.VINTAGE, 0.5))),
    Product(id="s7", name="Loafers", brand="Bass Weejuns", price=180,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["burgundy", "brown"],
            tags=["preppy"],
            archetype_weights=_w((Archetype.FORMAL, 0.6), (Archetype.VINTAGE, 0.8),
                                  (Archetype.MINIMALIST, 0.4))),
    Product(id="s8", name="Pegasus 41", brand="Nike", price=120,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["black", "blue"],
            tags=["running"],
            archetype_weights=_w((Archetype.SPORTY, 0.95),)),
    Product(id="s9", name="Derby shoe", brand="Church's", price=550,
            gender=Gender.MALE, slot=OutfitSlot.SHOES, colors=["black", "brown"],
            tags=["dress"],
            archetype_weights=_w((Archetype.FORMAL, 0.95), (Archetype.MINIMALIST, 0.5))),
    Product(id="s10", name="Suede desert boot", brand="Clarks", price=130,
            gender=Gender.UNISEX, slot=OutfitSlot.SHOES, colors=["sand", "brown"],
            tags=["heritage"],
            archetype_weights=_w((Archetype.VINTAGE, 0.75), (Archetype.MINIMALIST, 0.5))),
]


# ---- Sample quiz inputs ----

QUIZ_FORMAL_MALE = QuizAnswers(
    gender=Gender.MALE,
    budget_max=600.0,
    occasions=["work", "office"],
    style_selections=["minimalist", "classic"],
    season="autumn",
)

QUIZ_SPORTY_UNISEX = QuizAnswers(
    gender=Gender.UNISEX,
    budget_max=300.0,
    occasions=["sport", "casual"],
    style_selections=["sporty", "casual"],
    season="spring",
)

QUIZ_VINTAGE_UNISEX = QuizAnswers(
    gender=Gender.UNISEX,
    budget_max=500.0,
    occasions=["everyday"],
    style_selections=["vintage"],
)


COLOR_PROFILE_AUTUMN = ColorProfile(
    season="autumn",
    compatible_colors=["brown", "olive", "burgundy", "navy", "cream", "khaki"],
)
